CREATE ROLE super WITH LOGIN PASSWORD 'super';

CREATE ROLE team WITH LOGIN PASSWORD 'team' NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE DATABASE teams_database;
GRANT ALL PRIVILEGES ON DATABASE teams_database TO team ;
GRANT ALL PRIVILEGES ON DATABASE teams_database TO super;
