global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.

# tag::adocPrometheus[]
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
  - job_name: 'team'
    metrics_path: /rest-team/actuator/prometheus
    static_configs:
      - targets: ['127.0.0.1:8081']
# end::adocPrometheus[]
