version: "3"
services:
  database:
    image: "postgres:13.2"
    container_name: "soccer-database"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./db-init/initialize-databases.sql:/docker-entrypoint-initdb.d/init.sql
