version: "3"

services:
  sonarqube:
    image: sonarqube:8.2-community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    ports:
      - "9000:9000"
  db:
    image: postgres:13.2
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
